version: '3.8'

services:
  # web:
  #   build: ./web
  #   container_name: web
  #   ports:
  #     - "5173:5173"
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   stdin_open: true
  #   tty: true
  #   command: npm run dev -- --host 0.0.0.0
  # api:
  #   build: ./api
  #   container_name: api
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - ./api:/app
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   stdin_open: true
  #   tty: true
  #   command: [ "python", "app.py" ]
  express:
    build: ./express
    container_name: express
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    command: [ "npm", "run", "dev" ]
