version: '3.8'

services:
  web:
    build: ./web
    container_name: web
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    command: npm run dev -- --host 0.0.0.0
  api:
    build: ./api
    container_name: api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
    environment:
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true
    command: [ "python", "app.py" ]
  mobile:
    build: ./mobile
    container_name: mobile
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    volumes:
      - ./mobile:/app
      - /app/node_modules
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    stdin_open: true
    tty: true
    command: [ "npx", "expo", "start", "--tunnel" ]
