version: '3.8'

services:
  coffee-break-web:
    build: ./coffee-break-web
    container_name: coffee-break-web
    ports:
      - "5173:5173"
    # volumes:
    #   - ./coffee-break-web:/app
    #   - ./coffee-break-web/node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    command: npm run dev -- --host 0.0.0.0
  coffee-break-api:
    build: ./coffee-break-api
    container_name: coffee-break-api
    ports:
      - "5000:5000"
    volumes:
      - ./coffee-break-api:/app
    environment:
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true
    command: [ "python", "app.py" ]
